### ISSUE TITLE
Feature Idea: SyncAudio Playback

### ISSUE THREAD

**Issue by qwksilver** [FredTungsten/ScriptPlayer#107]
To be able to route a paired audio file, running in sync with the movie, to another output.
ex. main player sends audio to speakers, while script player sends the paired file to BT Headphones.

A useful example might be: English dub anime for the room, and original Japanese audio for the japanese friend that doesn't speak english well, and now no one needs subtitles.

In my setup, I have audio stim files that I use with an ET-312, while watching the paired movie.  Right now.  I have to play a file on an mp3 player, and the video on pc, and tinker a lot to sync it up perfectly.  If script player could do this, then it would allow the delay slider to fine tune the file to the video, and the perception of feels, while also allowing skipping to other points in the video, or changing video entirely, all without shifting the sync too much

I've looked high and low for a dual output video player and nothing seems to exist.  I put a request in for something similar with ZoomPlayer, but they think the implementation is too complicated.  I can easily route ZoomPlayer to speakers and VLC to headphones, and tweak each file, load two files in different locations, get them to the same time code, fix my home automation to send the play command to both in "nearly" perfect sync, and have to do it all over again to pick a new file, or to skip forward in the one i'm in.

With scriptplayers ability to look for a matching script with each file that ZoomPlayer opens, and to keep the script in sync with the video, well I think, why not look for WAV, MP3, AAC, and/or OGG, and play the audio time synced to the video to a specific output.  Then with only the script delay slider you can fine tune the file sync.

**Comment by FredTungsten** [comment]
Hmm .... that does sound complicated. I can't route the audio output of the video to a different audio device than the video, but with an external player handling the video it might work.

I might look into this some other time - it's rather complicated.

**Comment by qwksilver** [comment]
this would be more like loading a audio file paired to a video
so essentially a synced mp3 player.
so thisfunshow.mp4 would play on it's usual player (for me zoom)
and thisfunshow.wav would play on a second output from a second player (for me script player)

add a couple hot keys to adjust the delay on the fly and presto, perfect sync
add an audio waveform instead of script positions then visually easier to sync
have it write a paired file to save delay for each vid...and soon you are jumping from vid to vid at will.

**Comment by qwksilver** [comment]
I've considered this a little more.  I'm hoping it's somewhere close to development, a few thoughts might make this easier.  Phase 1: check for external video player, if in use enable these options
-Audio Sync Mode, looks for matched names with extensions wav, oog, and mp3.
-Keybinding to switch from script to audio matching
-There is already a keybinding for script sync matching

Phase 2: replace the heatmap with the waveform in audio mode

It's not necessary to have a whole audio output selector module, as I can force zoomplayer to use a specific output and let scriptplayer do the rest.  Other players might need audio routing to exist, i don't know.

Phase 3: might be making the player play two things, script and audio with video on the external, but right now I don't think a lot of people are going to have 3 way sync needs.

**Comment by qwksilver** [comment]
Just checking back in on this idea, also saw this: http://realtouchscripts.com/viewtopic.php?f=59&t=9190&p=25377&hilit=funstim#p25377 and thought a phase that implements realtime conversion from script to stimfiles.  But the first most important thing would be syncing playback of an mp3 or wav to the matched video(on another player).  :> anyway hope you are well in these trying times.

**Comment by FredTungsten** [comment]
Hi, yes I'm doing well - hope you too.
I really should work on my backlog of feature-requests, haven't touched anything since the last release 😞 
Syncing playback should be the easiest part so it would make sense to start there.
So far my knowledge about e-stim is very limited - do you know any good tutorials on how it works and is set up? (I understand the basic principle, that an audio-track is used to drive some special e-stim hardware that does the rest, but that's basically it)

**Comment by qwksilver** [comment]
Sync playback with volume and output selector would be a godsend all by its self, anything other features are just gravvvy.  I use smartstim.com for a community of stimmers to talk to.  No good instructional video, but if you don't mind a some explicit content.  [https://www.pornhub.com/view_video.php?viewkey=ph5cf03410240c2] will give you an idea of the setup and the audio.  I couldn't find one with more obvious audio, but some audio files fade back and forth between channel A & B, and that feels like being jerked off.  And there is no speed limit, beyond personal perception.

**Comment by FredTungsten** [comment]
I've just added an experimental audio generator with the latest commit. Via "Devices / Add E-Stim Audio", you can select the audio output device and what aspect of the sound is being changed (balance, volume or frequency). The usual settings in ScriptPlayer don't do anything yet. I don't know a lot about e-stim or audio but I hope this is a good starting point for e-stim integration (maybe someone with more knowledge on either topic comes to the rescue with a good PR :smile:)

**Comment by qwksilver** [comment]
sounds good, will check it out soon.

**Comment by qwksilver** [comment]
Out of the gate this is good, best mode is balance so far.  It would be good to scale the overall output in that mode volume based on the how fast the beat it, the faster beats are loosing strength in all modes.  So a being able to assign a boost % for yellow and another for red, or just for red and scale to different levels based on where the heat map would put it.

Volume mode seems very mono, would be good for 1 channel stim.  

Frequency doesn't respond well in any of my modes, and just feels like one constant signal.  Might work better for a 2b, or stereo stim user, but requires a combination of volume and "phase" to create sensations (save for last)

The single most distracting thing in session is the script delay doesn't work, so you can't align the script to the feel on the video.  i'm using BT and not a hard line audio cable so my processing time is close to 500-1500ms off.

after that, likely, would be settings. I would love to have control of
- Auto Start Audio Device as (select Vol, Bal, Freq) < same place as the auto launch for initface
For Volume/Balance Mode an audio panel & section
- Volume top and bottom percents
- Signal Frequency
- _Boost volume % for high "heat" (all modes)
<in balance mode only>
- Low swing of balance %(so 50% would be high L100R50 and low would be L50R100) and 25% would be L100R25 to L25R100
<in frequency mode only>
not sure what extra settings are useful here, maybe a top and bottom frequency, while volume is only a constant and not a range.

**Comment by qwksilver** [comment]
_Update to this: The single most distracting thing in session is the script delay doesn't work, so you can't align the script to the feel on the video. i'm using BT and not a hard line audio cable so my processing time is close to 500-1500ms off._

this is false, or was corrected somewhere, but I have been able to manually enter a lager delay and get them in sync.  I have a related issue of not being able to adjust by keyboard commands >500 but I entered a new issue for that.

Question:  is loading and syncing a mp3 file possible, while this is amazing, I still have a use for a sync  feature too.  Thanks. and also the rest of the previous comment about controls is still valid.

**Comment by FredTungsten** [comment]
> 
> Question: is loading and syncing a mp3 file possible, while this is amazing, I still have a use for a sync feature too. Thanks. and also the rest of the previous comment about controls is still valid.

Not yet - I don't know when I'll have time to do that but I'll let you know when it's done

**Comment by FredTungsten** [comment]
I've added a very experimental implementation for mp3 playback sync (wav doesn't work quite right yet - audio is very weird). In the "Estim Audio" panel of the settings dialog you can set the audio device for playback and the audio delay.

Don't expect anything to spectacular - I'm (as I've mentioned before) no expert in e-stim or audio related matters.

**Comment by qwksilver** [comment]
i'll check it soon

**Comment by qwksilver** [comment]
settings won't open at all, full crash when clicked

**Comment by FredTungsten** [comment]
There is a crash-log at `%AppData%\ScriptPlayer\Crash.log` (latest entry should be enough)

**Comment by qwksilver** [comment]
================= 6/1/2020 9:24:24 AM  =================
Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at System.Reflection.PropertyInfo.SetValue(Object obj, Object value)
   at ScriptPlayer.ViewModels.SettingsViewModel.Duplicate()
   at ScriptPlayer.Dialogs.SettingsDialog..ctor(SettingsViewModel initialSettings, String selectedPage)
   at ScriptPlayer.MainWindow.ShowSettings(String settingsId)
   at ScriptPlayer.MainWindow.ViewModelOnRequestShowSettings(Object sender, String settingsId)
   at ScriptPlayer.ViewModels.MainViewModel.OnRequestShowSettings(String settingsId)
   at ScriptPlayer.ViewModels.MainViewModel.ShowSettings(String settingsId)
   at ScriptPlayer.ViewModels.MainViewModel.ShowSettings()
   at ScriptPlayer.Shared.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
================= 6/1/2020 9:24:24 AM  =================
Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at System.Reflection.PropertyInfo.SetValue(Object obj, Object value)
   at ScriptPlayer.ViewModels.SettingsViewModel.Duplicate()
   at ScriptPlayer.Dialogs.SettingsDialog..ctor(SettingsViewModel initialSettings, String selectedPage)
   at ScriptPlayer.MainWindow.ShowSettings(String settingsId)
   at ScriptPlayer.MainWindow.ViewModelOnRequestShowSettings(Object sender, String settingsId)
   at ScriptPlayer.ViewModels.MainViewModel.OnRequestShowSettings(String settingsId)
   at ScriptPlayer.ViewModels.MainViewModel.ShowSettings(String settingsId)
   at ScriptPlayer.ViewModels.MainViewModel.ShowSettings()
   at ScriptPlayer.Shared.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at ScriptPlayer.App.Main()

**Comment by FredTungsten** [comment]
Huh ... that's odd. I don't really see how that would happen to be honest.  If the latest beta doesn't fix it I might have to wait until it happens to me to be able to fix it.

**Comment by qwksilver** [comment]
.280 opens settings.

**Comment by qwksilver** [comment]
Maybe related to not setting to default device correctly.

![settings flaw](https://user-images.githubusercontent.com/20508309/83415927-ef902780-a3ed-11ea-82d5-c4912de7d093.PNG)

I'll have to get to that machine to test actual audio.  That will be a little bit.

i'm assuming that a jump.(video file) will load and play jump.mp3 if it exists.  the osd reads "no script found".  the mp3 is in another directory (set by adding to the paths).  if they need to be in the same location, or if there are other conditions required to utilize this function let me know.  I'll be testing in about 1-2 hrs.

**Comment by qwksilver** [comment]
Inside Script player it works, it will even use the search paths and find video, script, and mp3 in three different folders.  With the script-to-estim driver taking priority over mp3 it seems. I watched it all in volume mixer.

on script-to-estim driver some more options would be nice. (see above)
https://github.com/FredTungsten/ScriptPlayer/issues/107#issuecomment-628863413

on mp3 sync playback these options would be nice

- #1 ability to use with external player(see below)
- separate volume in settings, a fixed amount should be ok, it shouldn't need adjusting once set.
- audio delay keybinding
- choice of priority (mp3 or script priority)(, or both together(idea for future separate automation))


on the external player sync, I couldn't get mp3 to run at all.  Script-to-estim is working well there.  I tried a bunch of stuff like file location, name & case matching, and so on, but no dice.  

funny story, I requested this a while back from zoom player, the ability to load a companion file and have it play to another audio out, they told me it couldn't be done in one player.  so congratulations you have done the impossible.  i told them it was to run the movie+english in main player and a companion Japanese mp3 to headphones staying in sync so everyone in the house could enjoy the same movie at the same time.  so a version of the player for just multilingual playback might be a marketable thing for you to sell.

**Comment by FredTungsten** [comment]
> 
>     * separate volume in settings, a fixed amount should be ok, it shouldn't need adjusting once set.
I might do this one next (next weekend at the earliest)

> 
>     * audio delay keybinding
Should already work

> 
>     * choice of priority (mp3 or script priority)(, or both together(idea for future separate automation))
 
> 
> on the external player sync, I couldn't get mp3 to run at all. Script-to-estim is working well there. I tried a bunch of stuff like file location, name & case matching, and so on, but no dice.
The mp3 playback is currently synced to local playback only but it shouldn't be to hard to sync it to external players - accuracy won't be great though

> 
> funny story, I requested this a while back from zoom player, the ability to load a companion file and have it play to another audio out, they told me it couldn't be done in one player. so congratulations you have done the impossible. i told them it was to run the movie+english in main player and a companion Japanese mp3 to headphones staying in sync so everyone in the house could enjoy the same movie at the same time. 

I can totally understand that from their standpoint. When you start mixing audio yourself, the whole neat driver stack provided by windows kind of falls apart. Even this very rudimentary implementation requires more hacky workarounds that I would normally be comfortable with.

>
> so a version of the player for just multilingual playback might be a marketable thing for you to sell.

I run this project with a "no money involved" policy (it's a pet project, I don't want to turn it into an obligation) - but if people want to use it like that, sure why not 😉 

Hopefully someone with e-stim and audio experience takes over this part, as I have neither and most of the things I added are just guesswork.

**Comment by qwksilver** [comment]
I guess I don't view audio routing the same way windows does, Mixing to me is combining serveral sources to one output with controls like gain, volume, eq pattern, and so on.  Routing is sending sources to specific outs.  Windows mixer is doing a good job of receiving what you are sending.

as for estim experience, the people that design the mp3 files they can create sensation the the script code itself doesn't  So the script code, and in particular the balance feature works really well to create an electronic emulation of a launch.  At any rate what's there now is working well, the tweaks are really just ideas for customization, and since each user is different, those fine tunes will eventually be very helpfull.

**Comment by qwksilver** [comment]
I'm closing this to create specific requests for better triage, also audio functions at two levels and has been quite nice.
