### ISSUE TITLE
Unable to connect to Intiface Server

### ISSUE THREAD

**Issue by smartu7** [FredTungsten/ScriptPlayer#141]
The ScriptPlayer is unable to connet to my local Intiface Server

- ScriptPlayer Version: 1.1.0
- Intiface Version: 16.0.0
- Windows 10 Version: 1909 (18363.900)

Both Scriptplayer and intiface ruuning on the same PC. Confirmed the intiface server works fine, syncydink is able to connect and Scriptplayer able to connect to intface from another Win10 PC, but which cannot connect from local.

Here is the  ERROR message:
`================= 2020/6/19 18:26:38  =================
Websocket Connection Exception! See Inner Exception
An unknown error occurred while connection to 'ws://localhost:12345/buttplug'. More detailed information in inner exception.

   at Buttplug.Client.Connectors.WebsocketConnector.ButtplugWebsocketConnector.<ConnectAsync>d__12.MoveNext()

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Buttplug.Client.ButtplugClient.<ConnectAsync>d__33.MoveNext()

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ScriptPlayer.Shared.ButtplugAdapter.<Connect>d__11.MoveNext()`

**Comment by FredTungsten** [comment]
If it works from another PC - try the local PC's IP instead of `localhost` (no idea why this would be happening)

**Comment by smartu7** [comment]
Tried, still not work, is this an Windows version matter issue? Another PC has different Win10 installed.

**Comment by FredTungsten** [comment]
I don't think so - I'm using the same version and it's working fine. Maybe Intiface doesn't bind to all network interfaces or fails because of some odd VPN, virtual interface (e.g. wireshark)? Maybe qDot (Intiface developer) has encountered this before:
https://github.com/qdot
