### ISSUE TITLE
ScriptPlayer will not launch. Fresh install from beta

### ISSUE THREAD

**Issue by hexplorer1** [FredTungsten/ScriptPlayer#216]
Hello, I installed the beta, and the application will not open. Here is the error log:

'The invocation of the constructor on type 'ScriptPlayer.MainWindow' that matches the specified binding constraints threw an exception.' Line number '12' and line position '9'.
Value cannot be null.
Parameter name: path1
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by hexplorer1** [comment]
I restarted my computer, and scriptplayer was the first thing to open. However, when I load up a video scriptplayer immediately crashes. Nothing new in the crash log though
