### ISSUE TITLE
local video player problem

### ISSUE THREAD

**Issue by breadfan69** [FredTungsten/ScriptPlayer#220]
If i load blind mode it will play scripts, but if a video is loaded the heat map blacks out and time says 0:00, and most of the time the program crashes.

Have updated system drivers, fresh install of scriptplayer latest beta, all codecs are up to date.....

Help!  

 Crash log: 
================= 2/15/2022 1:32:28 PM  =================
Unable to return a TimeSpan property value for a Duration value of 'Automatic'. Check the HasTimeSpan property before requesting the TimeSpan property value from a Duration.
   at System.Windows.Duration.get_TimeSpan()
   at ScriptPlayer.Shared.Controls.MediaWrapper.<PlayAndSeek>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ScriptPlayer.Shared.VideoPlayer.<CrossFade>d__136.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ScriptPlayer.Shared.VideoPlayer.<ProcessFileSeekEntry>d__120.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ScriptPlayer.Shared.VideoPlayer.<ProcessSeekEntry>d__119.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ScriptPlayer.Shared.VideoPlayer.<AddSeekEntry>d__118.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ScriptPlayer.Shared.VideoPlayer.<Open>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at ScriptPlayer.App.Main()

**Comment by FredTungsten** [comment]
That is very very odd ... and shouldn't be possible 😅

I've added a potential fix in the latest beta that should take care of the crash, but it might still mess something else further down the line.

Does this only happen with specific videos or all of them?
(If only specific ones: Are they streaming formats of regular mp4s or something?)

**Comment by breadfan69** [comment]
Thanks, I'll give this beta a try and report back.
Its happening with every video.  All of them played fine just last week.  Did not open scriptplayer for a few days and now this....

**Comment by breadfan69** [comment]
1.1.1.379 is not crashing, but still no video timestamp or heatmap
screenshot attached (i think?)

![spscreen](https://user-images.githubusercontent.com/99550910/154281466-c17520cf-9e11-4d67-aa3c-3b2485bb9c49.png)

**Comment by FredTungsten** [comment]
Odd ... does Windows Media Player still work?

**Comment by breadfan69** [comment]
Yes i can open the mp4 videos in media player and they play fine

**Comment by FredTungsten** [comment]
... sorry, but I have absolutely no idea why this would be happening 😞 
(That the last fix helped means that the integrated video player can't correctly load the video files)

Last thing you could try is disabling "Soft Seek" and "Auto-skip gaps" in the settings, but I'm not too confident that it will actually help.

**Comment by breadfan69** [comment]
No dice.  I do appreciate your effort.  
If you have a patreon i'd like to buy you a coffee (or beer!)

**Comment by FredTungsten** [comment]
Nope, but thanks for the offer

**Comment by breadfan69** [comment]
I downloaded zoom player and same deal, dunno if that helps sort the issue....

![image](https://user-images.githubusercontent.com/99550910/154302999-3c59b98b-d15c-45b0-874e-ea1288157523.png)

**Comment by breadfan69** [comment]
This will do as a workaround, i think.  Had to open the video through zoom player.
